#!/usr/bin/php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
  require __DIR__ . '/vendor/autoload.php';
} elseif (is_file(__DIR__ . '/../../autoload.php')) {
  require_once __DIR__ . '/../../autoload.php';
}

use Symfony\Component\Console\Application;
use wesleydv\DrupalUpgradeAudit\Compatibility;
use wesleydv\DrupalUpgradeAudit\Complexity;
use wesleydv\DrupalUpgradeAudit\Data;
use wesleydv\DrupalUpgradeAudit\DrupalCheck;
use wesleydv\DrupalUpgradeAudit\Git;
use wesleydv\DrupalUpgradeAudit\UpgradeAudit;
use wesleydv\DrupalUpgradeAudit\Version;
use GuzzleHttp\Client;

// Prepare.
$application = new Application();
$data = new Data();
$git = new Git($data);
$version = new Version($git);
$complexity = new Complexity($data);
$drupal_check = new DrupalCheck($data);
$client = new Client();
$compatibility = new Compatibility($data, $client);

// Setup application.
$application = new Application();
$application->add(new UpgradeAudit($data, $git, $version, $complexity, $drupal_check, $compatibility));
$application->setDefaultCommand('drupal-upgrade-audit', TRUE);
$application->run();
