#!/usr/bin/php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use wesleydv\DrupalUpgradeAudit\Compatibility;
use wesleydv\DrupalUpgradeAudit\Data;
use wesleydv\DrupalUpgradeAudit\DrupalCheck;
use wesleydv\DrupalUpgradeAudit\Git;
use wesleydv\DrupalUpgradeAudit\UpgradeAudit;

// Prepare.
$application = new Application();
$data = new Data();
$git = new Git($data);
$drupal_check = new DrupalCheck($data);
$compatibility = new Compatibility();

// Setup application.
$application = new Application();
$application->add(new UpgradeAudit($data, $git, $drupal_check, $compatibility));
$application->setDefaultCommand('upgrade-audit', TRUE);
$application->run();
